name: next_bus
description: A new Flutter project.
version: 1.2.0+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^8.1.0
  url_launcher: ^6.0.18
  cupertino_icons: ^1.0.4
  dio: ^3.0.0
  dio_flutter_transformer: ^3.0.2
  permission_handler: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: TransitBold
      fonts:
        - asset: assets/transit-bold.ttf
